---
name: Molecule
description: Run molecule test

inputs:
  arguments:
    description: The used molecule arguments.
    required: false
    default: test

runs:
  using: docker
  image: "docker://borisskert/molecule:v21.06.04"
  args:
    - "${{ inputs.arguments }}"
