---
name: Run tests

'on':
  push:
    tags:
      - v*

jobs:
  molecule_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: run molecule
        uses: borisskert/molecule-action@${GITHUB_REF#refs/tags/}
        with:
          arguments: --version
