---
name: Release

'on':
  push:
    tags:
      - v*
    branches-ignore:
      - '*'

jobs:
  molecule_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Set RELEASE_VERSION
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}

      - name: run molecule
        uses: borisskert/molecule-action@${{ env.RELEASE_VERSION }}
        with:
          arguments: --version
